### ISSUE TITLE
Infos manquantes dans le modèle : objet Quest 

### ISSUE THREAD

**Issue by HubertHamelin** [TeamBurtonPain/UrbanQuest#23]
Note de la Quest par les users (j'ai fait une fonction de calcul dans le script Quest Details : fichier Scripts puis UI)

Durée approximative de la quête (par les users aussi normalement)

Meilleur score de la quête (perso)

Titre de la quête ! (genre "campus de la Doua")

Etat d'avancement de la quête aussi

**Comment by pLOPeGG** [comment]
[x] Note de la Quest par les users (j'ai fait une fonction de calcul dans le script Quest Details : fichier Scripts puis UI)

[] Durée approximative de la quête (par les users aussi normalement)

[] Meilleur score de la quête (perso)

[] Titre de la quête ! (genre "campus de la Doua")
